# Example configuration file for blockchain-intent-solver
# Copy this file to config.yaml or config.yml and modify as needed
# Environment variables will override values in this file

# Base configuration
env: development
port: 3000

# MongoDB configuration
mongodb:
  uri: mongodb://localhost:27017/blockchain-intent-solver

# Redis configuration
redis:
  host: localhost
  port: 6379
  # password: your-redis-password  # Uncomment if using authentication

# Queue configuration
queue:
  defaultJobOptions:
    attempts: 3
    backoff:
      type: exponential
      delay: 1000

# AWS configuration (optional)
# aws:
#   region: us-east-1
#   secretName: my-secret-name
#   accessKeyId: your-access-key  # Better to use IAM roles or env vars
#   secretAccessKey: your-secret  # Better to use IAM roles or env vars

# Fulfillment configuration
fulfillment:
  defaultStrategy: standard
  strategies:
    standard:
      enabled: true
    crowdLiquidity:
      enabled: false
    nativeIntents:
      enabled: false
    negativeIntents:
      enabled: false
    rhinestone:
      enabled: false
  # Global default fees (OC-26 base)
  defaultFee:
    tokens:
      flatFee: 0.01          # e.g., 0.01 units (normalized via parseUnits in code paths that need it)
      scalarBps: 1           # 1 bps = 0.01%
    nonSwapTokens:
      flatFee: 0.008
      scalarBps: 0.8
    native:
      flatFee: 0.02          # e.g., 0.02 native (wei when used directly)
      scalarBps: 1.5         # 150 bps = 1.5%

  # Route-level per-pair overrides (OC-25)
  # Exact match only: sourceChainId+sourceToken -> destinationChainId+destinationToken
  # Example: treat USDC on OP to USDC on ETH as same-asset (nonSwapTokens); WETH->USDC as tokens
  routeFeeOverrides:
    - sourceChainId: '10'     # Optimism
      destinationChainId: '1' # Ethereum
      sourceToken: '0x0000000000000000000000000000000000000001'      # OP USDC (example)
      destinationToken: '0x0000000000000000000000000000000000000002' # ETH USDC (example)
      fee:
        tokens:
          flatFee: 0.005
          scalarBps: 0.5
        nonSwapTokens:
          flatFee: 0.003      # Lower for same-asset
          scalarBps: 0.3
        native:
          flatFee: 0.02
          scalarBps: 1.5

    - sourceChainId: '1'      # Ethereum
      destinationChainId: '10' # Optimism
      sourceToken: '0x0000000000000000000000000000000000000003'      # WETH (example)
      destinationToken: '0x0000000000000000000000000000000000000004' # USDC (example)
      fee:
        tokens:
          flatFee: 0.02
          scalarBps: 3.0
        nonSwapTokens:
          flatFee: 0.02
          scalarBps: 3.0
        native:
          flatFee: 0.02
          scalarBps: 1.5

# EVM configuration
evm:
  wallets:
    basic:
      # privateKey: 0x...  # Never commit private keys! Use env vars or AWS secrets
    # kernel:
    #   signer:
    #     type: eoa
    #     privateKey: 0x...  # Never commit private keys!

  # Example network configurations
  networks:
    - chainId: 1
      name: Ethereum Mainnet
      rpcUrls:
        - https://eth.llamarpc.com
      intentSource:
        address: '0x0000000000000000000000000000000000000000'
      listeners:
        - enabled: true
          startBlock: 0
          pollingInterval: 12000
      # Example token definitions (OC-26 nonSwapGroups)
      tokens:
        - address: '0x0000000000000000000000000000000000000002' # ETH USDC
          decimals: 6
          symbol: USDC
          nonSwapGroups: [ 'usdc' ]
        - address: '0x0000000000000000000000000000000000000004' # ETH USDC (for second example)
          decimals: 6
          symbol: USDC
          nonSwapGroups: [ 'usdc' ]

    - chainId: 10
      name: Optimism
      rpcUrls:
        - https://mainnet.optimism.io
      intentSource:
        address: '0x0000000000000000000000000000000000000000'
      listeners:
        - enabled: true
          startBlock: 0
          pollingInterval: 2000
      tokens:
        - address: '0x0000000000000000000000000000000000000001' # OP USDC
          decimals: 6
          symbol: USDC
          nonSwapGroups: [ 'usdc' ]
        - address: '0x0000000000000000000000000000000000000003' # OP WETH
          decimals: 18
          symbol: WETH

# Solana configuration
solana:
  network: mainnet-beta
  rpcUrl: https://api.mainnet-beta.solana.com
  # walletPrivateKey: base58-encoded-key  # Never commit! Use env vars
  # programId: YourProgramIdHere
  listeners:
    - enabled: false
      pollingInterval: 1000

# Prover configuration
provers:
  - type: hyper
    chainConfigs:
      - chainId: 1
        contractAddress: '0x0000000000000000000000000000000000000000'
      - chainId: 10
        contractAddress: '0x0000000000000000000000000000000000000000'

  # - type: metalayer
  #   chainConfigs:
  #     - chainId: 1
  #       contractAddress: "0x0000000000000000000000000000000000000000"
