services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eco-solver-app
    ports:
      - '3000:3000'
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      AWS_CONFIG_FILE: /root/.aws/config
      AWS_PROFILE: ${AWS_PROFILE}

      NODE_ENV: ${NODE_ENV:-development}
      NODE_CONFIG: |
        {
          "database": {
            "auth": {
              "enabled": false
            },
            "uriPrefix": "mongodb://",
            "uri": "mongodb:27017",
            "dbName": "eco-solver-local"
            },
          "redis": {
            "connection": {
              "host": "redis",
              "port": 6379
            }
          }
        }
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      - ~/.aws:/root/.aws:ro
    restart: unless-stopped
    command: ['yarn', 'start:dev']
    profiles: ['app', 'all']

  mongodb:
    image: mongo:8.0
    container_name: eco-solver-mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=eco-solver-local
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    profiles: ['db', 'all']

  redis:
    image: redis:7.4-alpine
    container_name: eco-solver-redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    profiles: ['db', 'all']

volumes:
  mongodb_data:
  redis_data:
