env: development
port: 3000

# Minimal config without any blockchain configuration
mongodb:
  uri: mongodb://localhost:27017/test

redis:
  host: localhost
  port: 6379

fulfillment:
  defaultStrategy: standard
  strategies:
    standard:
      enabled: true
EOF < /dev/null