/**
 * Job names for liquidity manager to break circular dependencies
 */
export enum LiquidityManagerJobName {
  REBALANCE = 'REBALANCE',
  CHECK_BALANCES = 'CHECK_BALANCES',
  CHECK_CCTP_ATTESTATION = 'CHECK_CCTP_ATTESTATION',
  EXECUTE_CCTP_MINT = 'EXECUTE_CCTP_MINT',
  CCTP_LIFI_DESTINATION_SWAP = 'CCTP_LIFI_DESTINATION_SWAP',
  CHECK_CCTPV2_ATTESTATION = 'CHECK_CCTPV2_ATTESTATION',
  EXECUTE_CCTPV2_MINT = 'EXECUTE_CCTPV2_MINT',
  CHECK_EVERCLEAR_INTENT = 'CHECK_EVERCLEAR_INTENT',
}